### ISSUE TITLE
SessionCommand--endSession测试问题

### ISSUE THREAD

**Issue by a65858835** [whaleal/mars#45]
测试需要传入UUID才能执行命令，传入后报出以下错误：
`org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded`
尝试以二进制的形式传入，传入后报出以下错误：
`com.mongodb.MongoCommandException: Command failed with error 14 (TypeMismatch): 'BSON field 'endSessions.endSessionsFromClient.id' is the wrong bindData type 'general', expected type 'UUID''`

**Comment by HbnKing** [comment]
需要额外测试  原生驱动的支持程度

**Comment by WhaleFalls0807** [comment]
经测试无误。出现这个错误的原因主要是未指定数据库的uuidRepresentation。

对于此问题的解决，有以下两种方式
1.在Mars的配置文件中设置uuidRepresentation类别
2.手动自定义MongoClientSettings，并设置uuidRepresentation类别，根据这个MongoClientSettings创建Mars
