### ISSUE TITLE
0.9.7. 事务异常

### ISSUE THREAD

**Issue by GitHubLhp123** [whaleal/mars#77]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-11-30 07:39:31.385 -org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter.report(LoggingFailureAnalysisReporter.java:40)  [           main] LoggingFailureAnalysisReporter : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method mongoTransactionManager in com.whaleal.mars.config.MarsAutoConfiguration required a bean of type 'com.whaleal.mars.codecs.MongoMappingContext' that could not be found.

Action:

Consider defining a bean of type 'com.whaleal.mars.codecs.MongoMappingContext' in your configuration.

Process finished with exit code 1

**Comment by GitHubLhp123** [comment]
应该是对 @transaction。支持的问题

**Comment by HbnKing** [comment]
影响范围 0.9.6-0.9.7   已于 0.9.8 版本处理
