### ISSUE TITLE
TooManyLogicalSessions Error

### ISSUE THREAD

**Issue by hanpengs** [whaleal/mars#81]
在一百个线程，使用Mars插入数据时，出现以下错误:
Cormand failed with error 261 (TooManyLogicalSessions): "Unable to add session ID c85b87ec-d97e-42c3-b819-d7859acc5b7d - Y5nrDaxi8gy8RndTsQ+1j7fnkr7JUsabhNnXAheU0fg- into the cache because the number of a
ctive sessions is too high" on server 172.233.72.34:27001. The full response is f"ok": 0.0, "errmsg": "Uhable to add session ID c85b87ec-d97e-42c3-b819-d7859acc5b7d - Y5mrDaxi8gv8RndTsQ+1j7fnkr7JUsabhNnXA
heUOfg= into the cache because the number of active sessions is too high", "code": 261, "codeName": "TooManyLogicalSessions"
com.mongodb.MongoConmandException: Command failed with error 261 (TooManylogicalSessions): "Unable to add session ID 32b60b4b-f3f3-42fa-b657-cbb6b8d2fd80 - Y5mrDaxi8gy8RndTsQ+1j7fnkr7JUsabhNnXAheU0fg- int
o the cache because the number of active sessions is too high" on server 172.233.72.34:27001. The full response is f"ok": 0.0, "errmsg": "Unable to add session ID 32b60b4b-f3f3-42fa-b657-cbb6b8d2fd80 - Y5
mrDaxi8gv8RndTsQ+1j7fmkr7JUsabhNmXAheUOfg- into the cache because the number of active sessions is too high", "code": 261, "codeName": "TooManyLogicalSessions"
at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175)

**Comment by HbnKing** [comment]
基于更新模式下 可以复现该问题 
update  当前有几个问题 
1. updatepipeline  未涉及完毕 
2. 自动 startSession   会导致 session激增

**Comment by HbnKing** [comment]
#93   相关问题关联
